CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    time_adding TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
