#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy
- name: docker compose build
  ansible.builtin.command: docker compose build
  args:
    chdir: ~/toDo1/app/
  changed_when: false

- name: docker compose up
  ansible.builtin.command: docker compose up -d
  args:
    chdir: ~/toDo1/app/
  changed_when: false
